import { Edit3, Save, X, Sparkles } from 'lucide-react';
import React, { useState, useRef, useEffect } from 'react';

import type { Character } from '@/types/character';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { cn } from '@/lib/utils';

export interface EditableDescriptionProps {
  /** The current value of the description field */
  value: string;
  /** The label to display above the field */
  label: string;
  /** Placeholder text when the field is empty */
  placeholder: string;
  /** The field name in the character object */
  field: keyof Character;
  /** The character object */
  character: Character;
  /** Callback function called when the character is updated */
  onUpdate: (updatedCharacter: Character) => void;
  /** Whether this field was generated by AI */
  isAiGenerated?: boolean;
  /** Additional CSS classes */
  className?: string;
  /** Minimum height for the textarea */
  minHeight?: string;
  /** Whether the component is disabled */
  disabled?: boolean;
}

/**
 * EditableDescription Component
 *
 * A reusable component for editing character description fields that can toggle
 * between read-only and editable modes. Shows visual indicators for AI-generated content.
 *
 * Features:
 * - Toggle between read-only and edit modes
 * - Auto-resize textarea based on content
 * - AI generation indicator badge
 * - Save/Cancel functionality
 * - Proper TypeScript types
 * - Consistent with project styling patterns
 */
const EditableDescription: React.FC<EditableDescriptionProps> = ({
  value = '',
  label,
  placeholder,
  field,
  character,
  onUpdate,
  isAiGenerated = false,
  className,
  minHeight = 'min-h-[100px]',
  disabled = false,
}) => {
  const [isEditing, setIsEditing] = useState(false);
  const [editValue, setEditValue] = useState(value);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Auto-resize textarea
  useEffect(() => {
    const textarea = textareaRef.current;
    if (textarea && isEditing) {
      textarea.style.height = 'auto';
      textarea.style.height = `${textarea.scrollHeight}px`;
    }
  }, [editValue, isEditing]);

  // Reset edit value when value prop changes
  useEffect(() => {
    setEditValue(value);
  }, [value]);

  // Focus textarea when entering edit mode
  useEffect(() => {
    if (isEditing && textareaRef.current) {
      textareaRef.current.focus();
      // Move cursor to end
      const length = textareaRef.current.value.length;
      textareaRef.current.setSelectionRange(length, length);
    }
  }, [isEditing]);

  const handleEdit = () => {
    if (!disabled) {
      setIsEditing(true);
    }
  };

  const handleSave = () => {
    onUpdate({
      ...character,
      [field]: editValue,
    });
    setIsEditing(false);
  };

  const handleCancel = () => {
    setEditValue(value);
    setIsEditing(false);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape') {
      handleCancel();
    } else if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
      handleSave();
    }
  };

  const handleTextareaChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setEditValue(e.target.value);
    // Auto-resize
    e.target.style.height = 'auto';
    e.target.style.height = `${e.target.scrollHeight}px`;
  };

  return (
    <div className={cn('space-y-2', className)}>
      {/* Label and AI Badge Row */}
      <div className="flex items-center justify-between">
        <Label className="text-sm font-medium text-muted-foreground">{label}</Label>
        <div className="flex items-center gap-2">
          {isAiGenerated && !isEditing && (
            <Badge
              variant="outline"
              className="text-xs bg-gradient-to-r from-purple-50 to-blue-50 border-purple-200 text-purple-700"
            >
              <Sparkles className="w-3 h-3 mr-1" />
              Generated by AI
            </Badge>
          )}
          {!isEditing && (
            <Button
              variant="ghost"
              size="sm"
              onClick={handleEdit}
              disabled={disabled}
              className="h-6 w-6 p-0 hover:bg-accent"
            >
              <Edit3 className="w-3 h-3" />
              <span className="sr-only">Edit {label}</span>
            </Button>
          )}
        </div>
      </div>

      {/* Content Area */}
      {isEditing ? (
        <div className="space-y-2">
          <Textarea
            ref={textareaRef}
            value={editValue}
            onChange={handleTextareaChange}
            onKeyDown={handleKeyDown}
            placeholder={placeholder}
            className={cn(
              minHeight,
              'resize-none transition-all duration-200 focus:ring-2 focus:ring-primary/20',
            )}
            rows={3}
          />
          <div className="flex items-center justify-end gap-2">
            <Button variant="outline" size="sm" onClick={handleCancel} className="h-8 px-3">
              <X className="w-3 h-3 mr-1" />
              Cancel
            </Button>
            <Button variant="default" size="sm" onClick={handleSave} className="h-8 px-3">
              <Save className="w-3 h-3 mr-1" />
              Save
            </Button>
          </div>
          <div className="text-xs text-muted-foreground">
            Press Ctrl+Enter to save, Escape to cancel
          </div>
        </div>
      ) : (
        <div
          className={cn(
            'relative rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background transition-colors',
            minHeight,
            'hover:bg-accent/50 cursor-pointer group',
            disabled && 'opacity-50 cursor-not-allowed hover:bg-background',
          )}
          onClick={handleEdit}
        >
          {value ? (
            <div className="whitespace-pre-wrap break-words leading-relaxed">{value}</div>
          ) : (
            <div className="text-muted-foreground italic">{placeholder}</div>
          )}

          {/* Hover Edit Indicator */}
          {!disabled && (
            <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
              <Edit3 className="w-3 h-3 text-muted-foreground" />
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default EditableDescription;
