/**
 * Error Codes Enum
 *
 * Standardized error codes for consistent error handling across the application.
 * These codes can be used by frontend to handle specific error cases.
 *
 * @module server/lib/error-codes
 */

/**
 * Standard error codes
 */
export enum ErrorCode {
  // Generic errors (400-499)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  BUSINESS_LOGIC_ERROR = 'BUSINESS_LOGIC_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // D&D 5E Combat errors
  COMBAT_NOT_ACTIVE = 'COMBAT_NOT_ACTIVE',
  COMBAT_ALREADY_ACTIVE = 'COMBAT_ALREADY_ACTIVE',
  PARTICIPANT_NOT_FOUND = 'PARTICIPANT_NOT_FOUND',
  INVALID_COMBAT_ACTION = 'INVALID_COMBAT_ACTION',
  NOT_PARTICIPANT_TURN = 'NOT_PARTICIPANT_TURN',

  // D&D 5E Spell errors
  INSUFFICIENT_SPELL_SLOTS = 'INSUFFICIENT_SPELL_SLOTS',
  INVALID_SPELL_LEVEL = 'INVALID_SPELL_LEVEL',
  CANNOT_UPCAST_CANTRIP = 'CANNOT_UPCAST_CANTRIP',
  INVALID_SPELL_SLOT_LEVEL = 'INVALID_SPELL_SLOT_LEVEL',

  // D&D 5E Character errors
  CHARACTER_DEAD = 'CHARACTER_DEAD',
  CHARACTER_UNCONSCIOUS = 'CHARACTER_UNCONSCIOUS',
  INSUFFICIENT_HP = 'INSUFFICIENT_HP',
  INVALID_HP_VALUE = 'INVALID_HP_VALUE',

  // D&D 5E Condition errors
  CONDITION_NOT_FOUND = 'CONDITION_NOT_FOUND',
  CONDITION_ALREADY_APPLIED = 'CONDITION_ALREADY_APPLIED',
  INVALID_CONDITION = 'INVALID_CONDITION',

  // D&D 5E Rest errors
  REST_NOT_ALLOWED = 'REST_NOT_ALLOWED',
  ALREADY_RESTED = 'ALREADY_RESTED',
  INSUFFICIENT_REST_TIME = 'INSUFFICIENT_REST_TIME',

  // D&D 5E Inventory errors
  ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
  INSUFFICIENT_QUANTITY = 'INSUFFICIENT_QUANTITY',
  INVENTORY_FULL = 'INVENTORY_FULL',
  CANNOT_EQUIP_ITEM = 'CANNOT_EQUIP_ITEM',

  // D&D 5E Progression errors
  INVALID_LEVEL = 'INVALID_LEVEL',
  INSUFFICIENT_EXPERIENCE = 'INSUFFICIENT_EXPERIENCE',
  MAX_LEVEL_REACHED = 'MAX_LEVEL_REACHED',

  // D&D 5E Class Features errors
  FEATURE_NOT_AVAILABLE = 'FEATURE_NOT_AVAILABLE',
  FEATURE_ALREADY_USED = 'FEATURE_ALREADY_USED',
  INSUFFICIENT_FEATURE_USES = 'INSUFFICIENT_FEATURE_USES',

  // Session errors
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_ENDED = 'SESSION_ENDED',
  SESSION_ALREADY_ACTIVE = 'SESSION_ALREADY_ACTIVE',
}
